### PR TITLE
add support to Laravel 5.1

### PR DESCRIPTION
**Pull request by luizreginaldo**

### CODE REVIEW

**Comment by dannydinges** [comment]
Can we have this merged please?

**Comment by luizreginaldo** [comment]
@dannydinges 

add this on the your composer.json

```
"repositories": 
 [
        {
            "type": "vcs",
            "url": "git@github.com:luizreginaldo/laravel-multi-tenant.git"
        }
]
```
and run ``composer update``

**Comment by tonglil** [comment]
1/4 of the tests did not complete because of a timeout. It would be great if this could be merged

**Comment by timkley** [comment]
+1

**Pull request merged**
