### PR TITLE
Updated to L5 with passed tests

### PR DESCRIPTION
**Pull request by AlanRezende**
since in L5 there is no findOrFail method in the model

### CODE REVIEW

**Comment by EspadaV8** [comment]
I've tried to apply this patch but it seems to fail with travis when applied ( https://travis-ci.org/EspadaV8/laravel-multi-tenant/jobs/53001441 )

**Comment by AlanRezende** [comment]
I don't know why is failing i tried with parent and static

**Comment by EspadaV8** [comment]
Ah ha. It seems to be related to the `ParentModel` class being within the `TenantScopedModelTraitTest` file.

**Comment by EspadaV8** [comment]
Okay. It works with the test case because it has it's own model that implements findOrFail. As soon as I try to have it extend the Laravel `Model` class a number of errors get thrown because of

```
Fatal error: Call to a member function make() on null in /home/vagrant/Code/laravel-multi-tenant/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 210

Call Stack:
    0.0003     227256   1. {main}() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/phpunit:0
    0.0340     861880   2. PHPUnit_TextUI_Command::main() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/phpunit:36
    0.0340     862504   3. PHPUnit_TextUI_Command->run() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/src/TextUI/Command.php:104
    0.0971    3617056   4. PHPUnit_TextUI_TestRunner->doRun() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/src/TextUI/Command.php:152
    0.1121    3955304   5. PHPUnit_Framework_TestSuite->run() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:398
    0.3449    7353120   6. PHPUnit_Framework_TestSuite->run() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/src/Framework/TestSuite.php:716
    0.3799    8334400   7. PHPUnit_Framework_TestCase->run() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/src/Framework/TestSuite.php:716
    0.3799    8334400   8. PHPUnit_Framework_TestResult->run() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/src/Framework/TestCase.php:693
    0.3799    8335408   9. PHPUnit_Framework_TestCase->runBare() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/src/Framework/TestResult.php:609
    0.3800    8352576  10. PHPUnit_Framework_TestCase->runTest() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/src/Framework/TestCase.php:737
    0.3800    8353392  11. ReflectionMethod->invokeArgs() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/src/Framework/TestCase.php:860
    0.3800    8353456  12. TenantScopedModelTraitTest->testFindOrFailThrowsTenantException() /home/vagrant/Code/laravel-multi-tenant/vendor/phpunit/phpunit/src/Framework/TestCase.php:860
    0.3800    8353736  13. TenantScopedModelStub::findOrFail() /home/vagrant/Code/laravel-multi-tenant/tests/TenantScopedModelTraitTest.php:37
    0.3800    8353768  14. Illuminate\Database\Eloquent\Model::query() /home/vagrant/Code/laravel-multi-tenant/src/AuraIsHere/LaravelMultiTenant/Traits/TenantScopedModelTrait.php:80
    0.3800    8354112  15. Illuminate\Database\Eloquent\Model->__construct() /home/vagrant/Code/laravel-multi-tenant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:632
    0.3800    8354376  16. Illuminate\Database\Eloquent\Model->bootIfNotBooted() /home/vagrant/Code/laravel-multi-tenant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:255
    0.3800    8354888  17. Illuminate\Database\Eloquent\Model::boot() /home/vagrant/Code/laravel-multi-tenant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:277
    0.3802    8355592  18. Illuminate\Database\Eloquent\Model::bootTraits() /home/vagrant/Code/laravel-multi-tenant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:307
    0.3803    8356776  19. forward_static_call() /home/vagrant/Code/laravel-multi-tenant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:321
    0.3803    8356840  20. TenantScopedModelStub::bootTenantScopedModelTrait() /home/vagrant/Code/laravel-multi-tenant/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:321
    0.3851    8398112  21. Illuminate\Support\Facades\App::make() /home/vagrant/Code/laravel-multi-tenant/src/AuraIsHere/LaravelMultiTenant/Traits/TenantScopedModelTrait.php:21
    0.3851    8398512  22. Illuminate\Support\Facades\Facade::__callStatic() /home/vagrant/Code/laravel-multi-tenant/src/AuraIsHere/LaravelMultiTenant/Traits/TenantScopedModelTrait.php:21
```

It looks like the `App` needs to be set up so that facades work, but I couldn't find anything going over that for package development/testing.

**Comment by EspadaV8** [comment]
I can definitely confirm this is an issue. Without this patch attempting to call findOrFail in Laravel 5 causes an infinite recursion

3tt7jlt

Alas, I'm not sure how to update the tests so that they pass once the PR has been merged. Any suggestions?

**Comment by AlanRezende** [comment]
@EspadaV8 The tests have been updated. All green!

**Comment by HipsterJazzbo** [comment]
I'm real sorry guys. I've been so slack. This won't actually work ATM, it's missing the `publishes()` call to publish the config on L5.

**Comment by EspadaV8** [comment]
Isn't that part of #33 ?

**Comment by HipsterJazzbo** [comment]
*A wild hipsterjazzbo has appeared!*

**Pull request merged**
