### PR TITLE
Import App and Config facades

### PR DESCRIPTION
**Pull request by jbrooksuk**
The aliases for `App` and `Config` may not exist, so we need to import the whole facade.

### CODE REVIEW

**Comment by jbrooksuk** [comment]
Ping @HipsterJazzbo :)

**Comment by HipsterJazzbo** [comment]
I know this needs to be changed, but I've been waiting to see what Taylor does for packages in L5, which he seems to have [nailed down today](http://laravel.com/docs/master/packages).

I'll close this in favour of working out a way to make it L4 and L5 friendly.

Thanks!

**Comment by jbrooksuk** [comment]
Check out [NotifyMe](https://github.com/notifymehq) we provide a bridge for L4 and L5. Either way, it'd be good to have this merged at least till you fully support L5 (and it's released). Without it, it's impossible to use if you don't load the facades in.

**Comment by HipsterJazzbo** [comment]
Well, in that case could you resubmit with just the facade tweaks and not including that code style stuff from the other PR?

**Comment by jbrooksuk** [comment]
Code style is still important ;)

I'll redo the facade stuff tomorrow now.

**Comment by HipsterJazzbo** [comment]
It sure is, but I've already merged it in #31

**Comment by jbrooksuk** [comment]
That's fine :)

Will make the facade changes again separately :)

**Pull request closed without merging**
