### PR TITLE
Update package to be compatible with Laravel 5

### PR DESCRIPTION
**Pull request by davidhemphill**
This updates the package to use the new config publishing and updates the TenantScope to include the new $model argument.

### CODE REVIEW

**Comment by HipsterJazzbo** [comment]
Awesome! Thanks for this. I'm planning to have two different service providers to support L4 and L5, so I'll leave this open til I get round to that.

**Comment by etiennemarais** [comment]
+1

**Comment by dieg0v** [comment]
+1

**Comment by EspadaV8** [comment]
Any ETA for the Laravel 5 service provider?

**Comment by HipsterJazzbo** [comment]
This should be all good with #40

**Pull request closed without merging**
